version: '2'
networks:
  default:
    external:
      name: vnet
services:
  kdi-1:
    image: mdrrakiburrahman/kdijava
    environment:
      KAFKA_TOPIC: server1.dbo.customers
      ADLS_STORAGE_ACCOUNT_NAME: ${ADLS_STORAGE_ACCOUNT_NAME}
      ADLS_STORAGE_CDC_CONTAINER_NAME: ${ADLS_STORAGE_CDC_CONTAINER_NAME}
      ADLS_CLIENT_ID: ${ADLS_CLIENT_ID}
      ADLS_CLIENT_SECRET: ${ADLS_CLIENT_SECRET}
      ADLS_CLIENT_TENANT: ${ADLS_CLIENT_TENANT}
      KAFKA_BROKER_ADDRESS: ${KAFKA_BROKER_ADDRESS}
      KAFKA_CONSUMER_NAME_SELF: ${KAFKA_CONSUMER_NAME_SELF}
  kdi-2:
    image: mdrrakiburrahman/kdijava
    environment:
      KAFKA_TOPIC: server1.dbo.orders
      ADLS_STORAGE_ACCOUNT_NAME: ${ADLS_STORAGE_ACCOUNT_NAME}
      ADLS_STORAGE_CDC_CONTAINER_NAME: ${ADLS_STORAGE_CDC_CONTAINER_NAME}
      ADLS_CLIENT_ID: ${ADLS_CLIENT_ID}
      ADLS_CLIENT_SECRET: ${ADLS_CLIENT_SECRET}
      ADLS_CLIENT_TENANT: ${ADLS_CLIENT_TENANT}
      KAFKA_BROKER_ADDRESS: ${KAFKA_BROKER_ADDRESS}
      KAFKA_CONSUMER_NAME_SELF: ${KAFKA_CONSUMER_NAME_SELF}
  kdi-3:
    image: mdrrakiburrahman/kdijava
    environment:
      KAFKA_TOPIC: server1.dbo.products
      ADLS_STORAGE_ACCOUNT_NAME: ${ADLS_STORAGE_ACCOUNT_NAME}
      ADLS_STORAGE_CDC_CONTAINER_NAME: ${ADLS_STORAGE_CDC_CONTAINER_NAME}
      ADLS_CLIENT_ID: ${ADLS_CLIENT_ID}
      ADLS_CLIENT_SECRET: ${ADLS_CLIENT_SECRET}
      ADLS_CLIENT_TENANT: ${ADLS_CLIENT_TENANT}
      KAFKA_BROKER_ADDRESS: ${KAFKA_BROKER_ADDRESS}
      KAFKA_CONSUMER_NAME_SELF: ${KAFKA_CONSUMER_NAME_SELF}
  kdi-4:
    image: mdrrakiburrahman/kdijava
    environment:
      KAFKA_TOPIC: server1.dbo.products_on_hand
      ADLS_STORAGE_ACCOUNT_NAME: ${ADLS_STORAGE_ACCOUNT_NAME}
      ADLS_STORAGE_CDC_CONTAINER_NAME: ${ADLS_STORAGE_CDC_CONTAINER_NAME}
      ADLS_CLIENT_ID: ${ADLS_CLIENT_ID}
      ADLS_CLIENT_SECRET: ${ADLS_CLIENT_SECRET}
      ADLS_CLIENT_TENANT: ${ADLS_CLIENT_TENANT}
      KAFKA_BROKER_ADDRESS: ${KAFKA_BROKER_ADDRESS}
      KAFKA_CONSUMER_NAME_SELF: ${KAFKA_CONSUMER_NAME_SELF}

