version: '3.2'
networks:
  default:
    external:
      name: vnet
services:
  kdi-customers:
    image: mdrrakiburrahman/kdijava
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      KAFKA_TOPIC: testDB.dbo.customers
      ADLS_STORAGE_ACCOUNT_NAME: ${ADLS_STORAGE_ACCOUNT_NAME}
      ADLS_STORAGE_CDC_CONTAINER_NAME: ${ADLS_STORAGE_CDC_CONTAINER_NAME}
      ADLS_CLIENT_ID: ${ADLS_CLIENT_ID}
      ADLS_CLIENT_SECRET: ${ADLS_CLIENT_SECRET}
      ADLS_CLIENT_TENANT: ${ADLS_CLIENT_TENANT}
      KAFKA_BROKER_ADDRESS: ${KAFKA_BROKER_ADDRESS}
      KAFKA_CONSUMER_NAME_SELF: ${KAFKA_CONSUMER_NAME_SELF}
  kdi-orders:
    image: mdrrakiburrahman/kdijava
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      KAFKA_TOPIC: testDB.dbo.orders
      ADLS_STORAGE_ACCOUNT_NAME: ${ADLS_STORAGE_ACCOUNT_NAME}
      ADLS_STORAGE_CDC_CONTAINER_NAME: ${ADLS_STORAGE_CDC_CONTAINER_NAME}
      ADLS_CLIENT_ID: ${ADLS_CLIENT_ID}
      ADLS_CLIENT_SECRET: ${ADLS_CLIENT_SECRET}
      ADLS_CLIENT_TENANT: ${ADLS_CLIENT_TENANT}
      KAFKA_BROKER_ADDRESS: ${KAFKA_BROKER_ADDRESS}
      KAFKA_CONSUMER_NAME_SELF: ${KAFKA_CONSUMER_NAME_SELF}
  kdi-products:
    image: mdrrakiburrahman/kdijava
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      KAFKA_TOPIC: testDB.dbo.products
      ADLS_STORAGE_ACCOUNT_NAME: ${ADLS_STORAGE_ACCOUNT_NAME}
      ADLS_STORAGE_CDC_CONTAINER_NAME: ${ADLS_STORAGE_CDC_CONTAINER_NAME}
      ADLS_CLIENT_ID: ${ADLS_CLIENT_ID}
      ADLS_CLIENT_SECRET: ${ADLS_CLIENT_SECRET}
      ADLS_CLIENT_TENANT: ${ADLS_CLIENT_TENANT}
      KAFKA_BROKER_ADDRESS: ${KAFKA_BROKER_ADDRESS}
      KAFKA_CONSUMER_NAME_SELF: ${KAFKA_CONSUMER_NAME_SELF}
  kdi-products_on_hand:
    image: mdrrakiburrahman/kdijava
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      KAFKA_TOPIC: testDB.dbo.products_on_hand
      ADLS_STORAGE_ACCOUNT_NAME: ${ADLS_STORAGE_ACCOUNT_NAME}
      ADLS_STORAGE_CDC_CONTAINER_NAME: ${ADLS_STORAGE_CDC_CONTAINER_NAME}
      ADLS_CLIENT_ID: ${ADLS_CLIENT_ID}
      ADLS_CLIENT_SECRET: ${ADLS_CLIENT_SECRET}
      ADLS_CLIENT_TENANT: ${ADLS_CLIENT_TENANT}
      KAFKA_BROKER_ADDRESS: ${KAFKA_BROKER_ADDRESS}
      KAFKA_CONSUMER_NAME_SELF: ${KAFKA_CONSUMER_NAME_SELF}